import mongoose from "mongoose";
import dotenv from "dotenv";
import Fact from "../models/Fact.js";

dotenv.config();

const facts = [
  { en: "Seafood is rich in protein and omega-3 fatty acids.", mr: "समुद्रातील अन्न प्रथिने आणि ओमेगा-३ फॅटी ऍसिडमध्ये समृद्ध आहे." },
  { en: "Fish oil helps improve brain function.", mr: "माशांचे तेल मेंदूचे कार्य सुधारण्यास मदत करते." },
  { en: "Shrimps are low in calories but high in nutrients.", mr: "कोळंबी कॅलरीमध्ये कमी पण पौष्टिकतेमध्ये जास्त आहे." },
  { en: "Seafood is good for heart health.", mr: "समुद्रातील अन्न हृदयाच्या आरोग्यासाठी चांगले आहे." },
  { en: "Tuna is a great source of vitamin D.", mr: "ट्यूना हे व्हिटॅमिन डीचे उत्कृष्ट स्त्रोत आहे." },
  { en: "Oysters contain zinc that boosts immunity.", mr: "ऑइस्टर्समध्ये झिंक असते जे रोगप्रतिकारशक्ती वाढवते." },
  { en: "Salmon supports healthy skin and hair.", mr: "सॅल्मन निरोगी त्वचा आणि केसांना मदत करते." },
  { en: "Crabs are rich in selenium and copper.", mr: "खेकडे सेलेनियम आणि तांब्यात समृद्ध असतात." },
  { en: "Regular seafood consumption lowers depression risk.", mr: "समुद्रातील अन्नाचे नियमित सेवन केल्याने नैराश्याचा धोका कमी होतो." },
  { en: "Sardines are packed with calcium and vitamin B12.", mr: "सार्डिन्स कॅल्शियम आणि व्हिटॅमिन B12 मध्ये भरलेले असतात." },
  { en: "Seafood is an excellent source of iodine.", mr: "समुद्रातील अन्न आयोडिनचे उत्कृष्ट स्त्रोत आहे." },
  { en: "Lobsters are high in vitamin B12 and phosphorus.", mr: "लॉब्स्टरमध्ये व्हिटॅमिन B12 आणि फॉस्फरस जास्त प्रमाणात असते." },
  { en: "Omega-3s from fish support vision health.", mr: "माशांमधील ओमेगा-३ दृष्टीच्या आरोग्यास मदत करतात." },
  { en: "Seaweed is a plant-based source of omega-3.", mr: "सीवीड हे वनस्पती-आधारित ओमेगा-३ चे स्त्रोत आहे." },
  { en: "Clams are rich in iron.", mr: "शिंपले लोहामध्ये समृद्ध असतात." },
  { en: "Eating seafood twice a week is recommended.", mr: "आठवड्यातून दोनदा समुद्रातील अन्न खाण्याची शिफारस केली जाते." },
  { en: "Seafood helps reduce inflammation.", mr: "समुद्रातील अन्न दाह कमी करण्यात मदत करते." },
  { en: "Octopus is a lean source of protein.", mr: "ऑक्टोपस प्रथिनांचे सडपातळ स्त्रोत आहे." },
  { en: "Mussels are high in vitamin C and iron.", mr: "शिंपले व्हिटॅमिन C आणि लोहामध्ये समृद्ध असतात." },
  { en: "Seafood improves blood circulation.", mr: "समुद्रातील अन्न रक्ताभिसरण सुधारते." },
  { en: "Anchovies are rich in calcium and omega-3.", mr: "अँकोव्हीज कॅल्शियम आणि ओमेगा-३ मध्ये समृद्ध असतात." },
  { en: "Eating fish may reduce asthma symptoms.", mr: "मासे खाल्ल्याने दमा लक्षणे कमी होऊ शकतात." },
  { en: "Seafood supports children's brain development.", mr: "समुद्रातील अन्न मुलांच्या मेंदूच्या विकासाला मदत करते." },
  { en: "Scallops are a good source of magnesium.", mr: "स्कॅलप्स मॅग्नेशियमचे उत्तम स्त्रोत आहेत." },
  { en: "Seafood helps lower triglyceride levels.", mr: "समुद्रातील अन्न ट्रायग्लिसराइड्सचे प्रमाण कमी करण्यात मदत करते." },
  { en: "Cod liver oil is a traditional remedy for joints.", mr: "कॉड लिव्हर ऑइल सांध्यांसाठी पारंपरिक औषध आहे." },
  { en: "Seafood enhances mood and reduces stress.", mr: "समुद्रातील अन्न मूड सुधारते आणि ताण कमी करते." },
  { en: "Squid is a low-fat protein source.", mr: "स्क्विड हे कमी चरबीयुक्त प्रथिनांचे स्त्रोत आहे." },
  { en: "Seafood supports healthy pregnancy.", mr: "समुद्रातील अन्न निरोगी गर्भधारणेला मदत करते." },
  { en: "Shellfish are high in antioxidants.", mr: "शेलफिश अँटीऑक्सिडंट्समध्ये जास्त असतात." },
  { en: "Seafood helps regulate blood pressure.", mr: "समुद्रातील अन्न रक्तदाब नियंत्रित करण्यात मदत करते." },
  { en: "Seafood provides essential amino acids.", mr: "समुद्रातील अन्न आवश्यक अमिनो ऍसिड्स पुरवते." },
  { en: "Eating fish reduces risk of Alzheimer's disease.", mr: "मासे खाल्ल्याने अल्झायमरचा धोका कमी होतो." },
  { en: "Seafood supports strong bones.", mr: "समुद्रातील अन्न मजबूत हाडांसाठी मदत करते." },
  { en: "Seafood helps maintain thyroid health.", mr: "समुद्रातील अन्न थायरॉईडच्या आरोग्यास मदत करते." },
  { en: "Crayfish are a source of vitamin E.", mr: "क्रेफिश हे व्हिटॅमिन ईचे स्त्रोत आहेत." },
  { en: "Seafood is beneficial for skin glow.", mr: "समुद्रातील अन्न त्वचेच्या तेजासाठी फायदेशीर आहे." },
  { en: "Seafood is naturally low in saturated fat.", mr: "समुद्रातील अन्न नैसर्गिकरित्या संतृप्त चरबीत कमी असते." },
  { en: "Seafood reduces risk of stroke.", mr: "समुद्रातील अन्नामुळे स्ट्रोकचा धोका कमी होतो." },
  { en: "Seafood boosts overall immunity.", mr: "समुद्रातील अन्न रोगप्रतिकारशक्ती वाढवते." },
  { en: "Seafood promotes healthy joints.", mr: "समुद्रातील अन्न निरोगी सांध्यांना प्रोत्साहन देते." },
  { en: "Seafood is a good source of vitamin A.", mr: "समुद्रातील अन्न व्हिटॅमिन एचे उत्तम स्त्रोत आहे." },
  { en: "Seafood supports cardiovascular health.", mr: "समुद्रातील अन्न हृदयविकाराच्या आरोग्यास मदत करते." },
  { en: "Seafood helps reduce chronic pain.", mr: "समुद्रातील अन्न दीर्घकालीन वेदना कमी करण्यात मदत करते." },
  { en: "Seafood contains minerals like potassium and magnesium.", mr: "समुद्रातील अन्नामध्ये पोटॅशियम आणि मॅग्नेशियम सारखी खनिजे असतात." },
  { en: "Seafood improves sleep quality.", mr: "समुद्रातील अन्न झोपेची गुणवत्ता सुधारते." },
  { en: "Seafood prevents iron deficiency.", mr: "समुद्रातील अन्न लोहाच्या कमतरतेपासून संरक्षण करते." },
  { en: "Seafood helps in muscle recovery.", mr: "समुद्रातील अन्न स्नायूंच्या पुनर्प्राप्तीत मदत करते." },
  { en: "Seafood is beneficial for eye health.", mr: "समुद्रातील अन्न डोळ्यांच्या आरोग्यासाठी फायदेशीर आहे." },
  { en: "Seafood reduces inflammation in the body.", mr: "समुद्रातील अन्न शरीरातील दाह कमी करते." },
  { en: "Seafood is an energy-boosting food.", mr: "समुद्रातील अन्न ऊर्जा वाढवणारे अन्न आहे." },
  { en: "Seafood supports liver health.", mr: "समुद्रातील अन्न यकृताच्या आरोग्यास मदत करते." },
  { en: "Seafood helps reduce blood clotting.", mr: "समुद्रातील अन्न रक्ताच्या गुठळ्या कमी करण्यात मदत करते." },
  { en: "Seafood reduces risk of obesity.", mr: "समुद्रातील अन्नामुळे लठ्ठपणाचा धोका कमी होतो." },
  { en: "Seafood helps in faster wound healing.", mr: "समुद्रातील अन्न जखम लवकर बरी करण्यात मदत करते." },
  { en: "Seafood contains essential micronutrients.", mr: "समुद्रातील अन्नामध्ये आवश्यक सूक्ष्मपोषक असतात." },
  { en: "Seafood helps boost concentration.", mr: "समुद्रातील अन्न एकाग्रता वाढवते." },
  { en: "Seafood reduces symptoms of arthritis.", mr: "समुद्रातील अन्न संधिवाताची लक्षणे कमी करते." },
  { en: "Seafood supports healthy metabolism.", mr: "समुद्रातील अन्न निरोगी चयापचयास मदत करते." },
  { en: "Seafood is a complete protein source.", mr: "समुद्रातील अन्न संपूर्ण प्रथिनांचे स्त्रोत आहे." },
  { en: "Seafood supports weight management.", mr: "समुद्रातील अन्न वजन व्यवस्थापनास मदत करते." },
  { en: "Seafood is beneficial for pregnant women.", mr: "समुद्रातील अन्न गर्भवती महिलांसाठी फायदेशीर आहे." },
  { en: "Seafood helps balance cholesterol levels.", mr: "समुद्रातील अन्न कोलेस्ट्रॉलचे प्रमाण संतुलित करण्यात मदत करते." },
  { en: "Seafood improves overall digestion.", mr: "समुद्रातील अन्न एकूण पचन सुधारते." },
  { en: "Seafood strengthens the immune response.", mr: "समुद्रातील अन्न रोगप्रतिकारक प्रतिसाद मजबूत करते." },
  { en: "Seafood prevents vitamin deficiency.", mr: "समुद्रातील अन्न व्हिटॅमिनच्या कमतरतेपासून वाचवते." },
  { en: "Seafood helps regulate hormones.", mr: "समुद्रातील अन्न हार्मोन्स नियंत्रित करण्यात मदत करते." },
  { en: "Seafood enhances memory power.", mr: "समुद्रातील अन्न स्मरणशक्ती वाढवते." },
  { en: "Seafood supports mental clarity.", mr: "समुद्रातील अन्न मानसिक स्पष्टतेला मदत करते." },
  { en: "Seafood helps fight fatigue.", mr: "समुद्रातील अन्न थकवा कमी करण्यात मदत करते." },
  { en: "Seafood is high in phosphorus.", mr: "समुद्रातील अन्न फॉस्फरस मध्ये जास्त असते." },
  { en: "Seafood supports red blood cell production.", mr: "समुद्रातील अन्न लाल रक्त पेशींच्या निर्मितीस मदत करते." },
  { en: "Seafood improves skin elasticity.", mr: "समुद्रातील अन्न त्वचेची लवचिकता सुधारते." },
  { en: "Seafood helps maintain healthy nails.", mr: "समुद्रातील अन्न निरोगी नखांसाठी मदत करते." },
  { en: "Seafood reduces aging signs.", mr: "समुद्रातील अन्न वृद्धत्वाची लक्षणे कमी करते." },
  { en: "Seafood is high in B vitamins.", mr: "समुद्रातील अन्न बी जीवनसत्त्वांमध्ये जास्त असते." },
  { en: "Seafood helps prevent anemia.", mr: "समुद्रातील अन्न रक्ताल्पता रोखण्यात मदत करते." },
  { en: "Seafood is light on the digestive system.", mr: "समुद्रातील अन्न पचनसंस्थेसाठी हलके असते." },
  { en: "Seafood is good for lung health.", mr: "समुद्रातील अन्न फुफ्फुसांच्या आरोग्यासाठी चांगले आहे." },
  { en: "Seafood boosts athletic performance.", mr: "समुद्रातील अन्न क्रीडापटूंची कामगिरी सुधारते." },
  { en: "Seafood prevents micronutrient deficiencies.", mr: "समुद्रातील अन्न सूक्ष्मपोषकांच्या कमतरतेपासून संरक्षण करते." },
  { en: "Seafood improves hormone balance.", mr: "समुद्रातील अन्न हार्मोनचे संतुलन सुधारते." },
  { en: "Seafood prevents cardiovascular disease.", mr: "समुद्रातील अन्न हृदयविकार टाळते." },
  { en: "Seafood helps maintain body hydration.", mr: "समुद्रातील अन्न शरीरातील पाण्याचे प्रमाण संतुलित ठेवते." },
  { en: "Seafood helps reduce PMS symptoms.", mr: "समुद्रातील अन्न पीएमएसची लक्षणे कमी करण्यात मदत करते." },
  { en: "Seafood supports faster metabolism.", mr: "समुद्रातील अन्न जलद चयापचयास मदत करते." },
  { en: "Seafood boosts brain sharpness.", mr: "समुद्रातील अन्न मेंदूची तीक्ष्णता वाढवते." },
  { en: "Seafood enhances skin hydration.", mr: "समुद्रातील अन्न त्वचेतील आर्द्रता वाढवते." },
  { en: "Seafood reduces heart attack risk.", mr: "समुद्रातील अन्न हृदयविकाराच्या झटक्याचा धोका कमी करते." },
  { en: "Seafood strengthens bones and joints.", mr: "समुद्रातील अन्न हाडे व सांधे मजबूत करते." },
  { en: "Seafood improves nervous system function.", mr: "समुद्रातील अन्न मज्जासंस्थेचे कार्य सुधारते." },
  { en: "Seafood boosts stamina and energy.", mr: "समुद्रातील अन्न सहनशक्ती आणि ऊर्जा वाढवते." },
  { en: "Seafood is nutrient-dense and filling.", mr: "समुद्रातील अन्न पोषक आणि पोटभर असते." },
  { en: "Seafood is naturally gluten-free.", mr: "समुद्रातील अन्न नैसर्गिकरित्या ग्लूटेन-मुक्त असते." },
  { en: "Seafood strengthens hair roots.", mr: "समुद्रातील अन्न केसांची मुळे मजबूत करते." },
  { en: "Seafood reduces joint stiffness.", mr: "समुद्रातील अन्न सांध्यांची कडकपणा कमी करते." },
  { en: "Seafood is high in healthy fats.", mr: "समुद्रातील अन्न निरोगी चरबीत जास्त असते." },
  { en: "Seafood lowers risk of chronic diseases.", mr: "समुद्रातील अन्न दीर्घकालीन रोगांचा धोका कमी करते." },
  { en: "Seafood boosts cell regeneration.", mr: "समुद्रातील अन्न पेशींची पुनर्निर्मिती वाढवते." },
  { en: "Seafood improves oxygen circulation.", mr: "समुद्रातील अन्न ऑक्सिजनचे रक्ताभिसरण सुधारते." },
  { en: "Seafood supports balanced diet.", mr: "समुद्रातील अन्न संतुलित आहारास मदत करते." },
  { en: "Seafood provides long-lasting energy.", mr: "समुद्रातील अन्न दीर्घकाळ टिकणारी ऊर्जा पुरवते." },
  { en: "Seafood is high in essential fatty acids.", mr: "समुद्रातील अन्न आवश्यक फॅटी ऍसिडमध्ये जास्त आहे." },
  { en: "Seafood helps prevent chronic inflammation.", mr: "समुद्रातील अन्न दीर्घकालीन दाह टाळते." },
  { en: "Seafood is beneficial for mental health.", mr: "समुद्रातील अन्न मानसिक आरोग्यासाठी फायदेशीर आहे." },
  { en: "Seafood strengthens the heart muscles.", mr: "समुद्रातील अन्न हृदयाचे स्नायू मजबूत करते." },
  { en: "Seafood helps in detoxification.", mr: "समुद्रातील अन्न डिटॉक्सिफिकेशनमध्ये मदत करते." },
  { en: "Seafood is a natural source of vitamin D.", mr: "समुद्रातील अन्न व्हिटॅमिन डीचा नैसर्गिक स्त्रोत आहे." },
  { en: "Seafood helps reduce migraine attacks.", mr: "समुद्रातील अन्न मायग्रेनचा त्रास कमी करण्यात मदत करते." },
  { en: "Seafood promotes healthy blood sugar levels.", mr: "समुद्रातील अन्न निरोगी रक्तातील साखरेचे प्रमाण प्रोत्साहन देते." },
  { en: "Seafood improves heart rhythm.", mr: "समुद्रातील अन्न हृदयाचा ठोका सुधारते." },
  { en: "Seafood reduces anxiety levels.", mr: "समुद्रातील अन्न चिंतेचे प्रमाण कमी करते." },
  { en: "Seafood strengthens the digestive tract.", mr: "समुद्रातील अन्न पचनसंस्था मजबूत करते." },
  { en: "Seafood reduces chronic fatigue.", mr: "समुद्रातील अन्न दीर्घकालीन थकवा कमी करते." },
  { en: "Seafood supports reproductive health.", mr: "समुद्रातील अन्न प्रजनन आरोग्यास मदत करते." },
  { en: "Seafood is high in antioxidants.", mr: "समुद्रातील अन्न अँटीऑक्सिडंट्समध्ये जास्त आहे." },
  { en: "Seafood reduces risk of autoimmune diseases.", mr: "समुद्रातील अन्न स्व-प्रत"},
];

const seedFacts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Fact.deleteMany(); // Clear existing facts
    await Fact.insertMany(facts); // Insert new facts
    console.log("✅ Facts seeded successfully");
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedFacts();
